version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./files/mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: code_challenge
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: codechallenger
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"